### ISSUE TITLE
Naming conventions for components

### ISSUE THREAD

**Issue by andyvesel** [fusor/mig-ui#33]
We need to reach some naming convention for components. In particular: do we want to name it like `SomeDataComponent` or just `SomeData` (considering also, putting that into components directory).

**Comment by andyvesel** [comment]
My suggestion here is: move all components under respective `components` directories and remove word `Component` from filenames

**Comment by andyvesel** [comment]
@eriknelson @ibolton336 @bond95 any opinion here?

**Comment by bond95** [comment]
> My suggestion here is: move all components under respective `components` directories and remove word `Component` from filenames

Agree, write every time `Component` is unnecessary, because file type `.tsx` by default mean that this is component, also every component start with uppercase, so if any function or class starts with capital letter it is component. `Component` word just increase size of file name. We in oVirt VM Portal doesn't have any additional words in component's names such as `Component`.

So I suggest to remove word `Component` from component's names.

**Comment by andyvesel** [comment]
That's a good point, thanks

**Comment by eriknelson** [comment]
We're still somewhat inconsistent on this. It's not a pressing issue, but it would be good to decide what we want to do here. I agree that I think we should remove `Component` as a suffix from components, as they're almost always inside of a component directory, so it's implicitly understood.

**Comment by eriknelson** [comment]
Closing this since we've been largely following the convention above with a few exceptions.
