### ISSUE TITLE
If a MigStorage fails to load, all of the MigStorages fail

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/mig-ui#362]
Turns out that if user have predefined `migstorages` with different relation between secret and the resource itself (naming does not match), the UI looses record of such resources.

**Comment by eriknelson** [comment]
The UI is grouping on `MigStorage` name rather than dereferencing the secret ref on the `MigStorage` object: https://github.com/fusor/mig-ui/blob/master/src/app/storage/duck/operations.ts#L200

This issue is two fold:
1) That grouping logic needs to be updated to follow the secret ref instead of just matching the names
2) This logic needs to be more resilient, so that if the dereferenced secret doesn't exist, it does not throw an unhandled exception that causes the rest of the storage objects to fail to load.
