### ISSUE TITLE
Plan watcher is using put request instead of patch

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/mig-ui#468]
The current implementation, which updates the migPlan state during different stages of the migration is based on `PUT` requests, which rewrites existing plan completely. This behaviour has some issues, one of them is that the status field get's purged every time when such update is executed.

The idea is to do the same set of actions, but by using the `PATCH` request instead, which will do it more mildly, and avoid described issues.

This also will allow to use existing resource as a source of truth, and will allow to gain more data about the plan for the mocked mig-controller in #442. In some occasions to delete the migplan, and decide if it needs a mocked mig-controller response, there is a need to look into the `status` of the migplan. When this information gets lost, mocks can't simulate constant watching and updates on the definition as the controllers do, which causes issues.

**Comment by eriknelson** [comment]
> The current implementation, which updates the migPlan state during different stages of the migration is based on PUT requests, which rewrites existing plan completely.

To be specific, it updates the plan during the MigPlan wizard. It shouldn't be writing to the plan at all during a migration.

> This behaviour has some issues, one of them is that the status field get's purged every time when such update is executed.

I don't think we should be moving to PATCH strictly because it clears the status. If the `spec` is updated for any reason, regardless of PUT or PATCH, the UI needs to be able to respond to status changes, and be able to determine when updated statuses are the result of a spec update and a controller reconciliation. The status could completely disappear for any reason, and the UI needs to be able to deal with that.

I think the bigger question is -- is PATCH a more correct HTTP verb for the operation we're doing? I think the answer is yes. It was probably using PUT in the first place in an effort to ensure the spec was maintained in its entirely, but what we're really doing is PATCHing an existing resource with some updates like a desired PV action or a storageclass designation.

This is going to require some UI code that ensures the patch is structured correctly so ONLY the new data is set.

**Comment by Danil-Grigorev** [comment]
I tested this on several migrations, where I tried the functionality on a plan closure and PV discovery, not noticing any issues. Basically previous implementation was doing the patching already, but did it locally, by copying all values from the existing resource on a new resource.

https://github.com/fusor/mig-ui/blob/511f0d55838d4772cd31b3f897746f5b5be51ecd/src/client/resources/conversions.ts#L244-L247

The kuberenetes documentation specifies that the existing deployment objects are updated by the patch request. https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/ The migPlan is close at it's functionality to a Deployment, it watches the state of migMigrations and do some functionality specified by it's definition. There is no info about usage of patch for other resources, but I don't see if such action is prohibited by some rule or kubernetes anti-pattern.

**Comment by Danil-Grigorev** [comment]
The part which is wrong on using `PUT`, is that the mig-ui is basically editing status fields on migPlan by every update, which is unrelated to the actual intended change. Those fields are managed by the mig-controller, and mig-ui should only read those.

**Comment by eriknelson** [comment]
> There is no info about usage of patch for other resources, but I don't see if such action is prohibited by some rule or kubernetes anti-pattern.

Both are acceptable ways to update k8s object. Most API objects are watched and reconciled, this is how kubernetes works. They are using the `Deployment` as an example to illustrate strategic merge patching, the kube extension to the JSON patch.

I'm fine with moving to PATCH to remain consistent with the rest of the app. But our PATCH should only contain the fields that we're expecting to update, not the entire object as it was done with PUT.

**Comment by eriknelson** [comment]
Discussed with @Danil-Grigorev, and after some more investigation and discussion, we feel that PUT is the correct request to use for updating the plan from inside the wizard. It atomically will update the full object with the **full** current state of the wizard's values.

There's still some investigation to be done re: status and whether or not that should be included in the object that is PUT.
